### ISSUE TITLE
アップル公証対応 (2020年2月3日以降、Catalina以降のOSで野良アプリが動作しなくなる可能性がある)

### ISSUE THREAD

**Issue by taku-o** [taku-o/myukkurivoice#206]
- セキュリティまわりに変化があり、アプリを提出しないといけないらしい
    - nortalize
    - さいわい、アプリの署名までは通してあるので、問題なく通るか？

```
Beginning in macOS 10.14.5, all new or updated kernel extensions and all software from developers 
new to distributing with Developer ID must be notarized in order to run. Beginning in macOS 10.15, 
notarization is required by default for all software.
```

**Comment by taku-o** [comment]
* Notarizing Your App Before Distribution
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution
 
* Upload Your App to the Notarization Service
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/customizing_the_notarization_workflow#3087734

**Comment by taku-o** [comment]
手順が多い
- https://uechi.io/blog/sign-and-notarize-electron-app

**Comment by taku-o** [comment]
Apple Storeに出すか、Apple公証か、
どちらかができれば良いみたい。

**Comment by taku-o** [comment]
- 準備。ただし、無問題に良いものでもなさそうだ。
- https://github.com/taku-o/myukkurivoice/pull/230

**Comment by taku-o** [comment]
アップル公証対応が2020年2月3日までに必要になった。
間に合うわけないだろ。(ツッコミ)

**Comment by taku-o** [comment]
good document
https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/
https://github.com/Nishkalkashyap/Quark-electron

**Comment by taku-o** [comment]
```

[22:31:02:0975] [warn] main:catch angularjs exception: Error: dlopen(/var/folders/3c/d6q3bmrx0qzf0r92_0t28_g40000gn/T/.52QJ97GWTE.jp.nanasi.myukkurivoice.3MIteR, 1): no suitable image found.  Did find:
	/var/folders/3c/d6q3bmrx0qzf0r92_0t28_g40000gn/T/.52QJ97GWTE.jp.nanasi.myukkurivoice.3MIteR: code signature in (/var/folders/3c/d6q3bmrx0qzf0r92_0t28_g40000gn/T/.52QJ97GWTE.jp.nanasi.myukkurivoice.3MIteR) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/var/folders/3c/d6q3bmrx0qzf0r92_0t28_g40000gn/T/.52QJ97GWTE.jp.nanasi.myukkurivoice.3MIteR: stat() failed with errno=17
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at bindings (/Users/taku-o/Downloads/MYukkuriVoice-darwin-x64/MYukkuriVoice.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
, cause:undefined
transportConsole @ /Users/taku-o/Downloads/MYukkuriVoice-darwin-x64/MYukkuriVoice.app/Contents/Resources/app.asar/node_modules/electron-log/index.js:1
/Users/taku-o/Downloads/MYukkuriVoice-darwin-x64/MYukkuriVoice.app/Contents/Resources/app.asar/node_modules/electron-log/index.js:1 [22:31:02:0978] [warn] main:catch angularjs exception: Error: dlopen(/var/folders/3c/d6q3bmrx0qzf0r92_0t28_g40000gn/T/.52QJ97GWTE.jp.nanasi.myukkurivoice.3MIteR, 1): no suitable image found.  Did find:
	/var/folders/3c/d6q3bmrx0qzf0r92_0t28_g40000gn/T/.52QJ97GWTE.jp.nanasi.myukkurivoice.3MIteR: code signature in (/var/folders/3c/d6q3bmrx0qzf0r92_0t28_g40000gn/T/.52QJ97GWTE.jp.nanasi.myukkurivoice.3MIteR) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at bindings (/Users/taku-o/Downloads/MYukkuriVoice-darwin-x64/MYukkuriVoice.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
```

**Comment by taku-o** [comment]
0.13.6で対応
